version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: personal-github-dashboard-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: github_dashboard
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: personal-github-dashboard-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command:
      - "redis-server"
      - "--maxmemory"
      - "256mb"
      - "--maxmemory-policy"
      - "allkeys-lru"
      - "--appendonly"
      - "yes"
      - "--save"
      - "900 1"
      - "300 10"
      - "60 10000"
    environment:
      - REDIS_AOF_ENABLED=yes
      - REDIS_SAVE=900 1 300 10 60 10000
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: personal-github-dashboard-backend
    container_name: personal-github-dashboard-backend
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/github_dashboard
      REDIS_URL: redis://redis:6379
      GITHUB_PERSONAL_ACCESS_TOKEN: ${GITHUB_PERSONAL_ACCESS_TOKEN}
      PORT: 8080
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: personal-github-dashboard-frontend
    container_name: personal-github-dashboard-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
