[package]
name = "github-dashboard"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.4.0"
actix-cors = "0.6.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.28", features = ["full"] }
diesel = { version = "2.0", features = ["sqlite"] }
dotenv = "0.15"
actix-ratelimit = "0.3"
env_logger = "0.10"
log = "0.4"
sqlx = { version = "0.7", features = ["runtime-tokio-rustls", "postgres", "chrono", "json"] }
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.4", features = ["v4", "serde"] }
redis = { version = "0.23", features = ["tokio-comp", "connection-manager"] }
futures = "0.3"
actix-session = "0.7"
actix-identity = "0.5"
bcrypt = "0.15"
jsonwebtoken = "9.1"
reqwest = { version = "0.11", features = ["json"] }