name: Backend CI

on:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/backend.yml'
  pull_request:
    paths:
      - 'backend/**'
      - '.github/workflows/backend.yml'

env:
  CARGO_TERM_COLOR: always
  DATABASE_URL: ${{ secrets.TEST_DATABASE_URL }}

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: personal_github_dashboard_dev
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      GITHUB_PERSONAL_ACCESS_TOKEN: ${{ secrets.GITHUB_PERSONAL_ACCESS_TOKEN }}
      TEST_DATABASE_URL: ${{ secrets.TEST_DATABASE_URL }}
      TEST_REDIS_URL: ${{ secrets.TEST_REDIS_URL }}
      GH_CLIENT_ID: ${{ secrets.GH_CLIENT_ID }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: backend

      - name: Install SQLx CLI
        run: cargo install sqlx-cli --no-default-features --features native-tls,postgres

      - name: Check Environment Variables
        run: |
          if [ -n "$TEST_REDIS_URL" ]; then
            echo "TEST_REDIS_URL is set"
          else
            echo "TEST_REDIS_URL is not set"
          fi

      - name: Create database
        run: sqlx database create

      - name: Run migrations
        working-directory: backend
        run: sqlx migrate run

      - name: Check formatting
        working-directory: backend
        run: cargo fmt --all -- --check

      - name: Run clippy
        working-directory: backend
        run: cargo clippy --all-targets --all-features -- -A warnings

      - name: Run tests
        working-directory: backend
        run: cargo test --all-features -- --include-ignored

      - name: Build
        working-directory: backend
        run: cargo build --release
