name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Install PostgreSQL
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql postgresql-contrib
          sudo systemctl start postgresql

      - name: Setup PostgreSQL
        run: |
          sudo -u postgres psql -c "CREATE USER postgres WITH PASSWORD 'postgres';"
          sudo -u postgres psql -c "CREATE DATABASE github_dashboard;"
          sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE github_dashboard TO postgres;"

      - name: Build Backend
        working-directory: ./backend
        run: |
          cargo build --release
          cargo test --release

      - name: Build Frontend
        working-directory: ./frontend
        run: |
          npm ci
          npm run build

      - name: Integration Test
        run: |
          cd backend
          cargo run --release &
          BACKEND_PID=$!
          sleep 5
          cd ../frontend
          npm run test:e2e
          kill $BACKEND_PID

      - name: Deploy Backend
        if: github.ref == 'refs/heads/main'
        working-directory: ./backend
        run: |
          # Add your deployment commands here
          echo "Deploying backend..."

      - name: Deploy Frontend
        if: github.ref == 'refs/heads/main'
        working-directory: ./frontend
        run: |
          # Add your deployment commands here
          echo "Deploying frontend..."
